### ISSUE TITLE
Email forwards 

### ISSUE THREAD

**Issue by hbbvf** [hbbvf/hbbvf.github.io#2]
Create email forwards for the hbbvf email account to the members of the board

**Comment by hbbvf** [comment]
A link will be sent to the email listed as a forward, which has to be confirmed (the link clicked) before the forwarding will occur.

**Comment by hbbvf** [comment]
Gmail only allows forwarding to one email address at a time, but seems this can be circumvented via filters.

**Comment by hbbvf** [comment]
Discuss with VF board how they want to do this. One forward or forward to all? Or maybe just create a filter than forwards to all and take it from there. I don't guess that there will be much traffic.

**Comment by hbbvf** [comment]
Only works with google groups if everyone has a google account (not gmail but an account with google).

**Comment by napps1** [comment]
Created filters to forward emails sent to VF account to the board members. Also, shared a link to the kontigent spreadsheet. 

Will need to find a more robust and smarter solution, but this will do for now.

**Comment by napps1** [comment]
Forward's are not working to Gisle and Jon. Need to follow up

**Comment by napps1** [comment]
Jon confirmed, awaiting confirmation from Eric (resent the 'let me forward emails to you').

**Comment by napps1** [comment]
Once Eric accepts, this will be done, so closing.
