### ISSUE TITLE
Add some basic visitor statistics to our home page (google analytics). 

### ISSUE THREAD

**Issue by hbbvf** [hbbvf/hbbvf.github.io#26]
https://www.simpleanalytics.com/glossary/google-analytics/integrate-google-analytics

Look at collecting (for free) some basic visitor statistics for our home page. Can see some info using Github Insights, but maximum value for stats is one month.

**Comment by hbbvf** [comment]
https://www.simpleanalytics.com/ - seems more privacy friendly than google and has a free tier available.

**Comment by hbbvf** [comment]
https://github.com/gayanvoice/github-profile-views-counter

**Comment by napps1** [comment]
Upon reflection, the data we publish is only really of interest for VF members. The free plans for collecting info on visits is typically only up to 30 days old. So, I will close this ticket. We can review if we think it's necessary.
