### ISSUE TITLE
Ask Thorbjørn to check through the HBBVF bank account

### ISSUE THREAD

**Issue by napps1** [hbbvf/hbbvf.github.io#4]
1 - Ask Thorbjørn if he can check the account (provide account number)

**Comment by hbbvf** [comment]
Email sent 2024-01-28, asking if Thorbjørn could take a look at the VF bank account.

**Comment by hbbvf** [comment]
All sorts of rules at the bank apparently, that prohibit Thorbjørn from being given access to an account that is in close proximity to him, which makes sense. So, we will need to history of the account, for at least, 2023 to be in order, such that we can ask him to review it. Once the account history is restored, we can print out the years transactions, and send it via email to Thorbjørn for him to review.

**Comment by napps1** [comment]
Managed to find the relevant transactions, and emailed them to Thorbjørn.

**Comment by napps1** [comment]
Sent a reminder, as a precursor to the årsmøte on Wednesday the 20th of March.

**Comment by napps1** [comment]
This is done for 2023.
